Goba Store/Controllers/CartController.cs
using Goba_Store.Application.View_Models;
using Goba_Store.DataAccess;
using Goba_Store.Models;
using Goba_Store.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Goba_Store.Controllers
{
    public class CartController : Controller
    {
        private readonly AppDbContext _db;
        public CartController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            List<ProductDetailsViewModel> ShoppingCartList = new List<ProductDetailsViewModel>();
            //get other products if there is any products in cart
            if (HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession) != null
                && HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession).ToList().Count > 0)
            {
                ShoppingCartList = HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList();
            }

            List<int> ProductsInCart = ShoppingCartList.Select(i => i.Product.Id).ToList();
            IEnumerable<CartProductViewModel> ProductsList = _db.Products.Where(p => ProductsInCart.Contains(p.Id))
                .Select(p => new CartProductViewModel
                {
                    Name = p.Name,
                    Price = p.Price,
                    ImageUrl = p.Image,
                    ShortDescription = p.ShortDescription,
                    Id = p.Id
                });

            return View(ProductsList);
        }

        [HttpGet]
        public IActionResult Summary()
        {
            List<ProductDetailsViewModel> ShoppingCartList = new List<ProductDetailsViewModel>();
            //get other products if there is any products in cart
            if (HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession) != null
               && HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession).ToList().Count > 0)
            {
                ShoppingCartList = HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList();
            }
            List<int> ProductsInCart = ShoppingCartList.Select(i => i.Product.Id).ToList();
            var ClaimsIdentity = (ClaimsIdentity)User.Identity;
            var Claims = ClaimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


            var viewModel = new SummeryViewModel {
            Products = _db.Products.Where(p => ProductsInCart.Contains(p.Id)).ToList(),
            User = _db.AppUser.FirstOrDefault(u=>u.Id == Claims.Value)

            };


            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddToCart(int id)
        {
                /*
            * 1-get cart session
            * 2-add item to it
            * 3-set new session
            */

            List<ProductDetailsViewModel> ShoppingCartList = new List<ProductDetailsViewModel>();
            //get other products if there is any products in cart
            if (HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession) != null
               && HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession).ToList().Count > 0)
            {
                ShoppingCartList = HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList();
            }
            //if this product is the first product in cart
            ShoppingCartList.Add(new ProductDetailsViewModel { Product = new Product {Id= id },InCart=true });
            HttpContext.Session.SetObj(Constants.CartSession, ShoppingCartList);
            return RedirectToAction("index","Home");
        }
        
        public IActionResult RemoveFromCart(int id,string? controllername)
        {
            /*
             * 1-get cart session
             * 2-remove item from it
             * 3-set new session
             */

            List<ProductDetailsViewModel> ShoppingCartList = new List<ProductDetailsViewModel>();
            if (HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession) != null
               && HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList().Count > 0)
            {
                ShoppingCartList = HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList();
            }

            var removedItem = ShoppingCartList.SingleOrDefault(i => i.Product.Id == id);

            if (removedItem != null)
                ShoppingCartList.Remove(removedItem);

            HttpContext.Session.SetObj(Constants.CartSession, ShoppingCartList);
            return RedirectToAction("index",controllername);
        }
        
        //TODO:Inquiry confirmation
    }
}

Goba Store/Controllers/CategoryController.cs
using AutoMapper;
using Goba_Store.Application.Services.Interfaces;
using Goba_Store.Application.View_Models;
using Goba_Store.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Goba_Store.Controllers;

[Authorize(Roles = Constants.AdminRole)]
public class CategoryController : Controller
{
    private readonly ICategoryService _categoryService;

    public CategoryController(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }
    // GET
    public IActionResult Index()
    {
        return View(_categoryService.GetAllCategories());
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CategoryViewModel viewModel )
    {
        if (ModelState.IsValid)
        {
            _categoryService.CreateCategory(viewModel);
            return RedirectToAction(nameof(Index));
        }
        return View(viewModel);
    }
    
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var category = _categoryService.GetCategoryById(id);
        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }


    [HttpPost]
    public IActionResult Edit(CategoryViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            _categoryService.UpdateCategory(viewModel);
            return RedirectToAction(nameof(Index));
        }

        return View(viewModel);
    }


    [HttpGet]
    public IActionResult Delete(int id)
    {
        var category = _categoryService.GetCategoryById(id);
        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        _categoryService.DeleteCategory(id);
        return RedirectToAction(nameof(Index));
    }
    
}

Goba Store/Controllers/ProductController.cs
using Goba_Store.Application.Services.Interfaces;
using Goba_Store.Application.View_Models;
using Goba_Store.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace Goba_Store.Controllers;

[Authorize(Roles = Constants.AdminRole)]
public class ProductController : Controller
{
    private readonly IProductService _productService;
    private readonly IWebHostEnvironment _environment;

    public ProductController(IProductService productService, IWebHostEnvironment environment)
    {
        _productService = productService;
        _environment = environment;
    }

    public IActionResult Index()
    {
        return View(_productService.GetAllProducts());
    }

    [HttpGet]
    [AllowAnonymous]
    public IActionResult Details(int id)
    {
        List<ProductDetailsViewModel> ShoppingCartList = new List<ProductDetailsViewModel>();
        if (HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession) != null
           && HttpContext.Session.GetObj<IEnumerable<ShoppingCartViewModel>>(Constants.CartSession).ToList().Count > 0)
        {
            ShoppingCartList = HttpContext.Session.GetObj<IEnumerable<ProductDetailsViewModel>>(Constants.CartSession).ToList();
        }
       return View(_productService.GetDetailsOfProductInCart(id, ShoppingCartList));
    }

    [HttpGet]
    public IActionResult Create()
    {
        ProductViewModel viewModel = new ProductViewModel();
        viewModel.CategoryDropDown = _productService.GetDropDownList();

        return View(viewModel);
    }

    [HttpPost]
    public IActionResult Create(ProductViewModel viewModel,[FromForm] IFormFileCollection files)
    {
        if (ModelState.IsValid)
        {
            _productService.CreateProduct(viewModel , files);
            return RedirectToAction(nameof(Index));
        }

        viewModel.CategoryDropDown = _productService.GetDropDownList();

        return View(viewModel);
    }


    [HttpGet]
    public IActionResult Edit(int id)
    {
        if (id == null || id == 0)
            return NotFound();
        var product = _productService.GetProductById(id);
        if (product == null)
            return NotFound();
        product.CategoryDropDown = _productService.GetDropDownList();
        return View(product);
    }
    [HttpPost]
    public IActionResult Edit(ProductViewModel viewModel , [FromForm] IFormFileCollection files)
    {
        if (ModelState.IsValid)
        {
            _productService.UpdateProduct(viewModel , files);
            return RedirectToAction("Index");
        }
        viewModel.CategoryDropDown = _productService.GetDropDownList();
        return View(viewModel);
    }


    [HttpGet]
    public IActionResult Delete(int id)
    {
        if (id == null || id == 0)
            return NotFound();
        var product = _productService.GetProductById(id);
        if (product == null)
            return NotFound();
        return View(product);
    }

    public IActionResult DeletePost(int id)
    {
        var product = _productService.GetProductById(id);
        if (product == null)
            return NotFound();;
        _productService.DeleteProduct(id);
        return RedirectToAction(nameof(Index));
    }

}

Goba Store/Views/Shared/_Layout.cshtml
@using Goba_Store.Application.View_Models
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Goba_Store.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Goba Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Goba_Store.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/sweetalert2/package/dist/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/summernote/summernote.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goba Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Constants.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">CMS</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown">
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="nav-link text-dark" style="font-size:11px" asp-area="Identity" asp-page="/Account/Register" >Create a Admin Account</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li>
                                @if (HttpContextAccessor.HttpContext.Session.GetObj<List<ShoppingCartViewModel>>(Constants.CartSession) != null)
                                {
                                    <a asp-action="Index" asp-controller="Cart">
                                        @{
                                            var shoppingCartItemsCount = HttpContextAccessor.HttpContext.Session.GetObj<List<ShoppingCartViewModel>>(Constants.CartSession).Count;
                                        }
                                        <i class="fa fa-shopping-cart"></i>&nbsp;(@shoppingCartItemsCount)
                                    </a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-controller="Cart" asp-action="Index">
                                        <i class="fa fa-shopping-cart"></i>&nbsp;(0)
                                    </a>
                                }
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="">
        <main role="main" class="" style="padding-bottom: 350px">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - Goba_Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/sweetalert2/package/dist/sweetalert2.all.min.js"></script>
    <script src="~/summernote/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Goba Store/Views/Shared/_ProductCard.cshtml
@model Product

<div class="card col-4 filter @Model.Category.Name.Replace(' ','_')" style="width: 16rem;margin-right: 15px">
  <img src="@Constants.ImagePath@Model.Image" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">@Model.Name</h5>
    <p class="card-text">@Model.ShortDescription</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Category : @Model.Category.Name</li>
    <li class="list-group-item">Price : @Model.Price $</li>
  </ul>
  <div class="card-body">
    <a style="width:100%" asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Details</a>
  </div>
</div>